# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94737e32d325ded11e28563be1af31be9c3d2aac97489525a24db8dc212ea65c00d9f1342951dcd1f7f04fb05c46c3b7c7821cdad947d4fd426257c9526b4328

test:
  secret_key_base: c6b4692fc049e51e3398d331329c3999b7bbd5975a100e09b2aa251bac4b8625f3f6b47401c6dd8759415bb01fd9d2e3a44553a7c7c16e98136c223bba65f8ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
